team: D&A Flexflow Operations Team
contact: pinto.b@pg.com, dragun.w@pg.com, DAOperations@shared.pg.com
agentPool: EX-VM-W-Prod
notifyBeforeDays: 14
resource:
  - keyvault:
      - adoServiceConnection: "Secrets rotation for ingestkvstorage"
        keyVault: "ingestkvstorage"
        secretNames:
          -
          -
  - keyvault:
      - adoServiceConnection: "Secrets rotation for kvingestionprod101"
        keyVault: "kvingestionprod101"
        secretNames:
          -
          -